### ISSUE TITLE
2.9 and 2.10 OpenGl error

### ISSUE THREAD

**Issue by jethornton** [LinuxCNC/linuxcnc#2642] opened 2023-09-16 18:49 UTC
## Here are the steps I follow to reproduce the issue:

 1. Install buildbot2 2.9 (latest one)
 2. Run the Axis Sim
 3.

## This is what I expected to happen:
Axis to run
## This is what happened instead:
Debug file information:
Note: Using POSIX realtime
note: MAXV     max: 5.000 units/sec 300.000 units/min
note: LJOG     max: 5.000 units/sec 300.000 units/min
note: LJOG default: 0.250 units/sec 15.000 units/min
note: jog_order='XYZ'
note: jog_invert=set()
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/OpenGL/latebind.py", line 43, in __call__
    return self._finalCall( *args, **named )
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/axis", line 3967, in <module>
    get_coordinate_font(vars.dro_large_font.get())
  File "/usr/bin/axis", line 3845, in get_coordinate_font
    glnav.use_pango_font(coordinate_font, 0, 128)
  File "/usr/lib/python3/dist-packages/glnav.py", line 65, in use_pango_font
    glBitmap(1, 0, 0, 0, 0, h-d, bytearray([0]*4))
  File "/usr/lib/python3/dist-packages/OpenGL/latebind.py", line 47, in __call__
    return self._finalCall( *args, **named )
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/OpenGL/wrapper.py", line 700, in wrapperCall
    raise err
  File "/usr/lib/python3/dist-packages/OpenGL/wrapper.py", line 693, in wrapperCall
    result = wrappedOperation( *cArguments )
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/OpenGL/platform/baseplatform.py", line 415, in __call__
    return self( *args, **named )
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/OpenGL/error.py", line 230, in glCheckError
    raise self._errorClass(
OpenGL.error.GLError: GLError(
	err = 1285,
	description = b'out of memory',
	baseOperation = glBitmap,
	pyArgs = (
		1,
		0,
		0,
		0,
		0,
		16.0,
		<OpenGL.arrays._buffers.Py_buffer object at 0x7f2a1b2d7da0>,
	),
	cArgs = (
		1,
		0,
		0,
		0,
		0,
		16.0,
		<OpenGL.arrays._buffers.Py_buffer object at 0x7f2a1b2d7da0>,
	),
	cArguments = (
		1,
		0,
		0,
		0,
		0,
		16.0,
		<OpenGL.arrays._buffers.Py_buffer object at 0x7f2a1b2d7da0>,
	)
)
272789
272841
Stopping realtime threads
Unloading hal components
Note: Using POSIX realtime

## It worked properly before this:
Uninstall buildbot or debs built from recent 2.9 or 2.10 and apt auto-remove then install from debian 12 and everything works as expected.

**Comment by rene-dev** [comment] 2023-09-16 20:33
Duplicate of #2510

**Closed** 2023-09-16 20:33 UTC
