### ISSUE TITLE
2.9 Gmoccapy - lathe_macros.ini is broken

### ISSUE THREAD

**Issue by zz912** [LinuxCNC/linuxcnc#3114] opened 2024-09-14 16:25 UTC
Hello,

I use RIP installation - 2.9 branche. Configuration /configs/sim/gmoccapy/lathe_configs/lathe_macros.ini is broken:
![lathe_macros](https://github.com/user-attachments/assets/e03d5c10-51ee-45ff-afa5-5aabfc45366f)

**Comment by hansu** [comment] 2024-09-14 18:27
@andypugh didn't you fix that some time ago?

**Comment by andypugh** [comment] 2024-09-15 10:10
It's working for me, and the 2.9.2 ISO install works too. 

I suspect a missing dependency, probably librsvg2-dev
https://github.com/LinuxCNC/linuxcnc/blob/54b6b75bbad1ecb968fe4369186798e2c083eb24/debian/control.main-pkg.in#L36

Maybe that shouldn't be in "recommends"? (though only the lathe macros need it, I think)

**Comment by zz912** [comment] 2024-09-15 18:03
I made:
sudo apt install librsvg2-dev
[terminal_output.txt](https://github.com/user-attachments/files/17006866/terminal_output.txt)

it did not help.

**Comment by andypugh** [comment] 2024-09-15 19:04
I am not sure if it is the cause, but can you check if you have python3-configobj? 

```
andypugh@rm-one:~/linuxcnc-dev/src$ sudo apt-cache policy python3-configobj
python3-configobj:
  Installed: 5.0.8-1
  Candidate: 5.0.8-1
  Version table:
 *** 5.0.8-1 500
        500 http://deb.debian.org/debian bookworm/main amd64 Packages
        500 http://deb.debian.org/debian bookworm/main armhf Packages
        500 http://deb.debian.org/debian bookworm/main i386 Packages
        100 /var/lib/dpkg/status
```

**Comment by zz912** [comment] 2024-09-15 19:11
I made
sudo apt install python3-configobj


It helped
![lathe](https://github.com/user-attachments/assets/c90a342a-2a7e-426b-8552-6e08e5beb64b)

Thank you.

**Comment by andypugh** [comment] 2024-09-15 19:17
Given that confgobj is a dependency in the Debian config:
https://github.com/LinuxCNC/linuxcnc/blob/2.9/debian/control.main-pkg.in#L23

I think we can close this?

**Closed** 2024-09-15 19:20 UTC
