### ISSUE TITLE
Inconsistent mode switching

### ISSUE THREAD

**Issue by pkmcnc** [LinuxCNC/linuxcnc#285] opened 2017-06-19 17:17 UTC
## Here are the steps I follow to reproduce the issue:

 1. Start a config (axis_mm)
 2. Power on the machine
 3. Switch to MDI mode

## This is what I expected to happen:
halui.mode-is-mdi activates

## This is what happened instead:
halui.mode.is-mdi activates for a short moment and then halui.mode.is-manual is active again.
If MDI command is executed the mode switches to MDI.

Also, the machine starts in manual mode, then switches to a different mode for a brief moment, then switches back to manual (I have a LED and a relay connected to halui.mode.is-manual so I can see and hear that).
Edit: The latter is not really confirmed. Probably the machine starts in some other mode and then switches to manual.

## It worked properly before this:
Not sure about 2.7

## Information about my hardware and software:

I am using Debian image.
I am running a binary I built myself from source.
I am using this LinuxCNC version v2.8.0-pre1-3169-gdf1c3ba

**Comment by rene-dev** [comment] 2017-12-01 17:57
seems to be axis related, cant reproduce this in gmoccapy.
works in 2.7 in axis.

**Comment by rene-dev** [comment] 2017-12-13 16:33
I think this can be closed., fixed by https://github.com/LinuxCNC/linuxcnc/commit/b7a13a899c59fb329602e2493d5edd07d3bf4244

**Closed** 2017-12-13 22:39 UTC
